# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run all python tests

on:
  push:
    branches: [ master, next-minor-release ]
  pull_request:
    branches: [ master, next-minor-release ]

jobs:
  lint:
    name: Linting using flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: .
          config: flake8.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pytest:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.7','3.8','3.9','3.10','3.11' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [[ $PYTHON_VERSION =~ ^2\.[0-9]+$ ]]; then pip install -r requirements/common.txt -r requirements/pip2.7.txt; fi
        if [[ $PYTHON_VERSION =~ ^3\.[0-9]+$ ]]; then pip install -r requirements/common.txt -r requirements/pip3.txt; fi
    - name: Test with pytest
      env:
        ONCOKB_API_TOKEN: ${{ secrets.ONCOKB_BOT_API_TOKEN }}
      run: |
        pytest

  build-in-windows:
    needs: lint
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.7','3.8','3.9','3.10','3.11' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if ( $env:PYTHON_VERSION -match '^2\.[0-9]+$' )
        {
          pip install -r requirements/common.txt -r requirements/pip2.7.txt
        }
        if ( $env:PYTHON_VERSION -match '^3\.[0-9]+$' )
        {
          pip install -r requirements/common.txt -r requirements/pip3.txt
        }
    - name: Test with pytest
      env:
        ONCOKB_API_TOKEN: ${{ secrets.ONCOKB_BOT_API_TOKEN }}
      run: |
        pytest
